export const API = {
  auth: {
    login: "/auth/login",
    me: "/auth/me",
    logout: "/auth/logout",
    changePassword: "/auth/change-password",
    verifyOtp: "/auth/verify-otp",
    meMenus: "/auth/me/menus",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
  },
  users: {
    list: "/users/list",
    create: "/users/create",
    delete: (id: number) => `/users/${id}`,
    update: (id: number) => `/users/${id}`,
    get: (id: number) => `/users/${id}`,
    departments: (id: number) => `/users/${id}/departments`,
    menus: (id: number) => `/users/${id}/menus`,
  },
  roles: {
    list: "/roles/list",
    create: "/roles/create",
    update: (id: number) => `/roles/${id}`,
    delete: (id: number) => `/roles/${id}`,
    assign: (roleId: number, userId: number) =>
      `/roles/${roleId}/assign/${userId}`,
  },
  menus: {
    list: "/menus/list",
    create: "/menus/create",
    update: (id: number) => `/menus/${id}`,
    delete: (id: number) => `/menus/${id}`,
    submenus: "/menus/submenus",
    updateSubmenu: (id: number) => `/menus/submenus/${id}`,
    deleteSubmenu: (id: number) => `/menus/submenus/${id}`,
    subsubmenus: "/menus/subsubmenus",
    updateSubsubmenu: (id: number) => `/menus/subsubmenus/${id}`,
    deleteSubsubmenu: (id: number) => `/menus/subsubmenus/${id}`,
  },
  invoices: {
    all: "/invoices/all",
    detail: (id: number) => `/invoices/details/${id}`,
    create: "/invoices/create",
    summary: "/invoices/summary",
  },
  clientInvoices: {
    all: "/client-invoices/all",
    detail: (id: number | string) => `/client-invoices/details/${id}`,
    create: "/client-invoices/create",
  },
  subcontractorInvoices: {
    all: "/subcontractor-invoices/all",
    detail: (id: number) => `/subcontractor-invoices/details/${id}`,
    create: "/subcontractor-invoices/create",
  },
  companyInvoices: {
    all: "/company-invoices/all",
    detail: (id: number | string) => `/company-invoices/details/${id}`,
    create: "/company-invoices/create",
  },
  workers: {
    listBySite: (siteId: number) => `/workers/list-by-id/${siteId}`,
    detail: (id: number) => `/workers/details/${id}`,
    update: (id: number) => `/workers/update/${id}`,
    skills: "/workers/skills",
    createSkill: "/workers/skills/create",
  },
  sites: {
    list: "/sites/list",
    create: "/sites/create",
    detail: (id: number) => `/sites/${id}`,
    update: (id: number) => `/sites/${id}`,
    updateEstimatedValue: (id: number) => `/sites/${id}/estimated-value`,
    analytics: (id: number | string) => `/sites/analytics/${id}`,
    dashboardMetrics: "/sites/dashboard-metrics",
    unassignedOperators: "/sites/operators/unassigned",
    assignOperator: (siteId: number | string, operatorId: number | string) =>
      `/sites/${siteId}/operator/${operatorId}`,
    operator: (siteId: number | string) => `/sites/${siteId}/operator`,
    replaceOperator: (siteId: number | string) => `/sites/${siteId}/operator/replace`,
  },
  materials: {
    unitAll: "/materials/unit/all",
    unitCreate: "/materials/unit/create",
    materialAdd: "/materials/material/add",
    toolAdd: "/materials/tool/add",
  },
  attendance: {
    summary: "/attendance/summary",
    analytics: "/attendance/analytics",
    checkIn: "/attendance/check-in",
    payrollSummary: "/attendance/payroll-summary",
  },
  tasks: {
    listBySite: (siteId: number) => `/tasks/list/${siteId}`,
    create: "/tasks/task/create",
    update: (taskId: number) => `/tasks/task/update/${taskId}`,
    listSubtasksByTask: (taskId: number) => `/tasks/sub-task/list/${taskId}`,
    createSubtask: "/tasks/sub-task/create",
    updateSubtask: (subtaskId: number) => `/tasks/sub-task/update/${subtaskId}`,
  },
  analytics: {
    overview: "/analytics/overview",
  },
  departments: {
    list: "/departments/list",
    create: "/departments/create",
    detail: (id: number) => `/departments/${id}`,
    menus: (id: number) => `/departments/${id}/menus`,
    members: (id: number) => `/departments/${id}/members`,
    users: (id: number) => `/departments/${id}/users`,
    assignUsers: (id: number) => `/departments/${id}/assign-users`,
  },
  permits: {
    myPermits: "/permits/my-pemits", 
    all: "/permits/all",
    get: (id: number) => `/permits/get/${id}`,
    create: "/permits/create",
    submit: (id: number) => `/permits/submit/${id}`,
    takeAction: (id: number) => `/permits/take-action/${id}`,
    pending: "/permits/pending",
    categories: "/permits/categories",
    createCategory: "/permits/category/create",
    updateCategory: (id: number) => `/permits/category/${id}`,
  },
  stores: {
    summary: (siteId: number) => `/store/site/${siteId}`,
    materials: (siteId: number) => `/store/materials/${siteId}/all`,
    tools: (siteId: number) => `/store/tools/${siteId}/all`,
    totals: '/store/store/totals',
    dailyUsageAll: '/daily-usage/all',
    dailyUsage: (usageId: number) => `/daily-usage/${usageId}`,
    dailyUsageOrders: (usageId: number) => `/daily-usage/orders/${usageId}`,
  },
   transport: {
    vehicleCategories: "/transport/categories",
    createVehicleCategory: "/transport/categories/create",
    updateVehicleCategory: (id: number) => `/transport/categories/${id}`,
    modesOfTransport: "/transport/vehicles",
    createModeOfTransport: "/transport/vehicles/create",
    updateModeOfTransport: (id: number) => `/transport/vehicles/${id}`,
  },
  invoiceActions: {
    updateStatus: (invoiceType: string, invoiceId: number | string) =>
      `/invoices/${invoiceType}/${invoiceId}/status`,
    recordPayment: (invoiceType: string, invoiceId: number | string) =>
      `/invoices/${invoiceType}/${invoiceId}/payments`,
    paymentHistory: (invoiceType: string, invoiceId: number | string) =>
      `/invoices/${invoiceType}/${invoiceId}/payments`,
  },
} as const;