export const API = {
  auth: {
    login: "/auth/login",
    me: "/auth/me",
    logout: "/auth/logout",
    changePassword: "/auth/change-password",
    verifyOtp: "/auth/verify-otp",
  },
  users: {
    list: "/users/list",
    create: "/users/create",
    delete: (id: number) => `/users/${id}`,
    update: (id: number) => `/users/${id}`,
    get: (id: number) => `/users/${id}`,
    departments: (id: number) => `/users/${id}/departments`,
    menus: (id: number) => `/users/${id}/menus`,
  },
  roles: {
    list: "/roles/list",
    create: "/roles/create",
    update: (id: number) => `/roles/${id}`,
    delete: (id: number) => `/roles/${id}`,
    assign: (roleId: number, userId: number) =>
      `/roles/${roleId}/assign/${userId}`,
  },
  menus: {
    list: "/menus/list",
    create: "/menus/create",
    update: (id: number) => `/menus/${id}`,
    delete: (id: number) => `/menus/${id}`,
    submenus: "/menus/submenus",
    updateSubmenu: (id: number) => `/menus/submenus/${id}`,
    deleteSubmenu: (id: number) => `/menus/submenus/${id}`,
    subsubmenus: "/menus/subsubmenus",
    updateSubsubmenu: (id: number) => `/menus/subsubmenus/${id}`,
    deleteSubsubmenu: (id: number) => `/menus/subsubmenus/${id}`,
  },
  invoices: {
    all: "/invoices/all",
    detail: (id: number) => `/invoices/details/${id}`,
    create: "/invoices/create",
  },
  companyInvoices: {
    all: "/company-invoices/all",
    detail: (id: number) => `/company-invoices/details/${id}`,
    create: "/company-invoices/create",
  },
  permits: {
    myPermits: "/permits/my-pemits",
    all: "/permits/all",
    get: (id: number) => `/permits/get/${id}`,
    create: "/permits/create",
    submit: (id: number) => `/permits/submit/${id}`,
    takeAction: (id: number) => `/permits/take-action/${id}`,
    pending: "/permits/pending",
    categories: "/permits/categories",
    createCategory: "/permits/category/create",
    updateCategory: (id: number) => `/permits/category/${id}`,
  },
  workers: {
    listBySite: (siteId: number) => `/workers/list-by-id/${siteId}`,
    detail: (id: number) => `/workers/details/${id}`,
    update: (id: number) => `/workers/update/${id}`,
    skills: "/workers/skills",
    createSkill: "/workers/skills/create",
  },
 sites: {
    list: "/sites/list",
    create: "/sites/create",
    detail: (id: number) => `/sites/${id}`,
  },
  tasks: {
    list: (siteId: number) => `/tasks/list/${siteId}`,
    create: "/tasks/task/create",
    subtasks: {
      list: (taskId: number) => `/tasks/sub-task/list/${taskId}`,
      create: "/tasks/sub-task/create",
    },
  },
  departments: {
    list: "/departments/list",
    create: "/departments/create",
  },
  stores: {
    summary: (siteId: number) => `/store/site/${siteId}`,
    materials: (siteId: number) => `/store/materials/${siteId}/all`,
    tools: (siteId: number) => `/store/tools/${siteId}/all`,
    dailyUsageAll: '/daily-usage/all',
    dailyUsage:    (usageId: number) => `/daily-usage/${usageId}`,
    dailyUsageOrders: (usageId: number) => `/daily-usage/orders/${usageId}`,
  },
} as const;