export const ROUTES = {
  home:     '/home',
  signin:   '/signin',
  account:  '/account',
  users: {
    dashboard: '/users/dashboard',
    new:    '/users/new',
    roles:  '/users/roles',
    assign: '/users/roles/assign',
    reports:'/users/reports',
    imports:'/users/import',
  },
  finance: {
    home:     '/finance',
    invoices: '/finance/invoice/supplier',
    new:      '/finance/invoices/new',
    dashboard: '/finance/dashboard',
    templates: '/finance/templates',
    invoiceClient:     '/finance/invoice/client',
    invoiceCompany:    '/finance/invoice/company',
    invoiceContractor: '/finance/invoice/contractor',
  },
  projects: {
    dashboard: '/projects/dashboard',
    new:       '/projects/new',
    sites:     '/projects/sites',
  },
  quality: {
    dashboard: '/quality/dashboard',
  },
  permits: {
    all:              '/permits/all',
    create:           '/permits/create',
    myPendingPermits: '/permits/my-pending-permits',
    myPermits:        '/permits/my-permits',
  },
  sections: {
    departments: '/sections/departments',
    menus:       '/sections/menus',
  },
  stores: {
    dashboard: '/stores/dasboard', 
    stocks:    '/stores/stocks',
    materials: (siteId: number) => `/stores/materials/${siteId}`,
    tools:     (siteId: number) => `/stores/tools/${siteId}`,
    orders:    '/stores/orders',
    orderDetail: (usageId: number) => `/stores/orders/${usageId}`,
  },
  workers:    '/workers',
  store:      '/store',
  department: '/department',
} as const;