export enum DriverTaskType {
  TRANSFER = 'TRANSFER',
  SUPPLIER_PICKUP = 'SUPPLIER_PICKUP',
}

export enum DriverTaskStatus {
  PENDING_ASSIGNMENT = 'PENDING_ASSIGNMENT',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}